USE PIZZARIA;
GO

CREATE TABLE T_CLIENTE
(
	ID_CLIENTE UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	NM_CLIENTE NVARCHAR(70) NOT NULL,
	NU_TELEFONE NVARCHAR(11) NOT NULL
)	
GO

CREATE TABLE T_ENDERECO
(
	ID_ENDERECO UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	NM_LOGRADOURO NVARCHAR(150) NOT NULL,
	DS_NUMERO_ENDERECO NVARCHAR(10) NOT NULL,
	DS_COMPLEMENTO NVARCHAR(150) NULL,
	DS_BAIRRO NVARCHAR(50) NOT NULL,
	DS_CIDADE NVARCHAR(50) NOT NULL,
	DS_ESTADO NVARCHAR(50) NOT NULL,
	DS_CEP NVARCHAR(8) NOT NULL,
	CD_CLIENTE UNIQUEIDENTIFIER
)
GO

CREATE TABLE T_PRODUTO
(
	ID_PRODUTO UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	NM_PRODUTO NVARCHAR(50) NOT NULL,
	DS_PRODUTO NVARCHAR(100) NULL,
	VL_PRODUTO MONEY NOT NULL,
	NU_QTD_PRODUTO INT NULL,
	CD_CATEGORIA UNIQUEIDENTIFIER
)
GO

CREATE TABLE T_CATEGORIA
(
	ID_CATEGORIA UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	DS_CATEGORIA NVARCHAR(50) NOT NULL
) 
GO

ALTER TABLE T_ENDERECO
ADD CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (CD_CLIENTE)
REFERENCES T_CLIENTE (ID_CLIENTE)
GO

ALTER TABLE T_PRODUTO
ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (CD_CATEGORIA)
REFERENCES T_CATEGORIA (ID_CATEGORIA)
GO

